- hosts: all
  name: APT

  tasks:

    - name: Refresh APT repo
      # Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: Install Add APT packages
      apt: pkg={{ item }} state=installed update_cache=true install_recommends=yes
      sudo: yes
      with_items:
        - vim
        #used for Varnish
        - varnish
        - apt-transport-https
# https://gorails.com/setup/ubuntu/14.04
# gem install rubyXL
#        - git-core
#        - curl
#        - zlib1g-dev
#        - build-essential
#        - libssl-dev
#        - libreadline-dev
#        - libyaml-dev
#        - libsqlite3-dev
#        - sqlite3
#        - libxml2-dev
#        - libxslt1-dev
#        - libcurl4-openssl-dev
#        - python-software-properties
#        - openssl
#        - ruby-rvm
