---
- hosts: all
  name: Configuration
  vars:

    # Magento

    local_magento_local_xml_path: ../files/magento/local.xml
    local_magento_domains_path: ../files/magento/domains.php

    remote_magento_local_xml_path: /usr/share/nginx/www/magento/web-root/app/etc
    remote_magento_domains_path: /usr/share/nginx/www/magento/web-root

    remote_magento_shell_path: /usr/share/nginx/www/magento/web-root/shell

    # Wordpress

    local_wordpress_wpconfig_path: ../files/wordpress/wp-config.php
    remote_wordpress_wpconfig_path: /usr/share/nginx/www/wordpress/content

  tasks:

    - name: Include Configuration
      include_vars: ../../ansiblealexa.yml

    # Wordpress

    - name: Copy Wordpress Configuration
      template: src={{ local_wordpress_wpconfig_path }} dest={{ remote_wordpress_wpconfig_path }} force=true
      sudo: yes

    # Magento

    - name: Template Magento Local.xml
      template: src={{ local_magento_local_xml_path }} dest={{ remote_magento_local_xml_path }} force=true
      sudo: yes

    - name: Template Magento Domains.php
      template: src={{ local_magento_domains_path }} dest={{ remote_magento_domains_path }} force=true
      sudo: yes

    - name: Reindex Magento "Catalog Product Flat"
      command: php {{ remote_magento_shell_path }}/indexer.php --reindex catalog_product_flat

    - name: Reindex Magento "Catalog Category Flat"
      command: php {{ remote_magento_shell_path }}/indexer.php --reindex catalog_category_flat

    - name: Reindex Magento "Catalog Category Product"
      command: php {{ remote_magento_shell_path }}/indexer.php --reindex catalog_category_product

    - name: Reindex Magento "Catalog Product Prices"
      command: php {{ remote_magento_shell_path }}/indexer.php --reindex catalog_product_price

    - name: Reindex Magento "Catalog Product Attributes"
      command: php {{ remote_magento_shell_path }}/indexer.php --reindex catalog_product_attribute

    - name: Reindex Magento "Catalog URL"
      command: php {{ remote_magento_shell_path }}/indexer.php --reindex catalog_url

    - name: Reindex Magento "Catalog Inventory Stock"
      command: php {{ remote_magento_shell_path }}/indexer.php --reindex cataloginventory_stock