---
- hosts: all
  name: MySQL
  vars:

    db_magento_remote_path: /var/magento.sql
    db_wordpress_remote_path: /var/wordpress.sql

    db_magento_local_path: ../files/database/magento.sql
    db_wordpress_local_path: ../files/database/wordpress.sql

    # Local

    local_my_cnf_path: ../files/mysql/my.cnf

    # Remote

    remote_my_cnf_path: /etc/mysql

  tasks:

    - name: Include Configuration
      include_vars: ../../ansiblealexa.yml

    # Installation

    - name: Install MySQL Server
      apt: pkg=mysql-server state=installed update_cache=true
      sudo: yes

    - name: Install MySQL-Python
      apt: pkg=python2.7-mysqldb state=installed update_cache=true
      sudo: yes

    - name: Ensure MySQL Running
      service: name=mysql state=started enabled=true

    # Users

    - name: Setup Local MySQL User
      mysql_user: name={{ db_username_root }} host=localhost password={{ db_password }} priv=*.*:ALL,GRANT state=present
      ignore_errors: yes

    - name: Setup Remote MySQL User
      mysql_user: name={{ db_username_remote }} host=% password={{ db_password }}
                  priv=*.*:ALL,GRANT state=present
                  login_password={{ db_password }} login_user={{ db_username_root }}

    - name: Copy MySQL Configuration
      template: src={{ local_my_cnf_path }} dest={{ remote_my_cnf_path }} owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Restarting MySQL Server
      service: name=mysql state=restarted enabled=true
      sudo: yes

    # Database dumps

    - name: Check Magento Database
      mysql_db: name={{ db_name_magento }} state=present
                login_password={{ db_password }} login_user={{ db_username_root }}
      notify: Template Magento DB

    - name: Check Wordpress Database
      mysql_db: name={{ db_name_wordpress }} state=present
                login_password={{ db_password }} login_user={{ db_username_root }}
      notify: Template Wordpress DB

  handlers:

    # Magento

    - name: Template Magento DB
      template: src={{ db_magento_local_path }} dest={{ db_magento_remote_path }} owner=root group=root mode=0644
      notify: Import Magento
      sudo: yes

    - name: Import Magento
      mysql_db: name={{ db_name_magento }} state=import target={{ db_magento_remote_path }}
                login_password={{ db_password }} login_user={{ db_username_root }}
      notify: Remove Magento Copied DB
      sudo: yes

    - name: Remove Magento Copied DB
      command: rm -f {{ db_magento_remote_path }}
      sudo: yes

    # Wordpress

    - name: Template Wordpress DB
      template: src={{ db_wordpress_local_path }} dest={{ db_wordpress_remote_path }} owner=root group=root mode=0644
      notify: Import Wordpress
      sudo: yes

    - name: Import Wordpress
      mysql_db: name={{ db_name_wordpress }} state=import target={{ db_wordpress_remote_path }}
                login_password={{ db_password }} login_user={{ db_username_root }}
      notify: Remove Wordpress Template DB
      sudo: yes

    - name: Remove Wordpress Template DB
      command: rm -f {{ db_wordpress_remote_path }}
      sudo: yes