---
- hosts: all
  name: MySQL
  vars:

      user_email: adam@alexandalexa.com

      mysql_username: root
      mysql_password: ansiblealexa

      db_wordpress: wordpress
      db_magento: magento

      host_magento: magento.alexandalexa.com
      host_wordpress: wordpress.alexandalexa.com

      db_wordpress_path: ~/wordpress.sql

  tasks:

    # Installation

    - name: Install MySQL Server
      apt: pkg=mysql-server state=installed update_cache=true
      sudo: yes

    - name: Install MySQL-Python
      apt: pkg=python2.7-mysqldb state=installed update_cache=true
      sudo: yes

    - name: Ensure MySQL Running
      service: name=mysql state=started enabled=true

    # Users

    - name: Setup Local MySQL User
      mysql_user: name={{ mysql_username }} host=localhost password={{ mysql_password }} priv=*.*:ALL,GRANT state=present
      ignore_errors: yes

    - name: Setup Remote MySQL User
      mysql_user: name=developer host=% password={{ mysql_password }}
                  priv=*.*:ALL,GRANT state=present
                  login_password={{ mysql_password }} login_user={{ mysql_username }}

    - name: Copy MySQL Configuration
      copy: src=../files/mysql/my.cnf dest=/etc/mysql owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Restarting MySQL Server
      service: name=mysql state=restarted enabled=true
      sudo: yes

    # Database dumps

    - name: Check Wordpress Database
      mysql_db: name={{ db_wordpress }} state=present
                login_password={{ mysql_password }} login_user={{ mysql_username }}
      notify: Replace Variables

  handlers:

    - name: Template Wordpress DB
      template: src=../../database/wordpress.sql dest={{ db_wordpress_path }} owner=root group=root mode=0644
      notify: Import Wordpress
      sudo: yes

    - name: Import Wordpress
      mysql_db: name={{ db_wordpress }} state=import target={{ db_wordpress_path }}
                login_password={{ mysql_password }} login_user={{ mysql_username }}