---
- hosts: all
  name: MySQL
  vars:
      mysql_password: password123

  tasks:

    - name: Install MySQL Server
      apt: pkg=mysql-server state=installed update_cache=true
      sudo: yes

    - name: Install MySQL-Python
      apt: pkg=python2.7-mysqldb state=installed update_cache=true
      sudo: yes

    - name: Ensure MySQL Running
      service: name=mysql state=started enabled=true

    - name: Setup Root MySQL
      mysql_user: name=root host=localhost password={{ mysql_password }} priv=*.*:ALL,GRANT state=present

    - name: Setup Remote MySQL
      mysql_user: name=developer host=% password={{ mysql_password }}
                  priv=*.*:ALL,GRANT state=present login_password={{ mysql_password }} login_user=root

    - name: Copy MySQL Configuration
      copy: src=../../provision/mysql/my.cnf dest=/etc/mysql owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Restarting MySQL Server
      service: name=mysql state=restarted enabled=true
      sudo: yes

#
#    - name: copy .my.cnf file with root password credentials
#      template: src=templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600
#
#    - name: update mysql root password for all root accounts
#      mysql_user: name=root host={{ item }} password={{ root_db_password }}
#      with_items:
#        - {{ ansible_hostname }}
#        - 127.0.0.1
#        - ::1
#
#    - name: ensure anonymous users are not in the database
#      mysql_user: name='' host={{ item }} state=absent
#      with_items:
#        - localhost
#        - {{ inventory_hostname }}
#
#    - name: remove the test database
#      mysql_db: name=test state=absent