---
- hosts: all
  name: MySQL
  vars:

    db_magento_remote_path: /var/magento-core.sql
    db_wordpress_remote_path: /var/{{ item }}.sql

    db_magento_local_path: ../files/database/magento-core.sql
    db_wordpress_local_path: ../files/database/{{ item }}.sql

    # Local

    local_my_cnf_path: ../files/mysql/my.cnf

    # Remote

    remote_my_cnf_path: /etc/mysql

  tasks:

    - name: Include Configuration
      include_vars: ../../ansiblealexa.yml

    # Installation

    - name: Install MySQL Server
      apt: pkg=mysql-server state=installed update_cache=true force=true
      sudo: yes

    - name: Install MySQL-Python
      apt: pkg=python2.7-mysqldb state=installed update_cache=true
      sudo: yes

    - name: Ensure MySQL Running
      service: name=mysql state=started enabled=true

    # Users

    - name: Setup Local MySQL User
      mysql_user: name={{ db_username_root }} host=localhost password={{ db_password }} priv=*.*:ALL,GRANT state=present
      ignore_errors: yes

    - name: Setup Remote MySQL User
      mysql_user: name={{ db_username_remote }} host=% password={{ db_password }}
                  priv=*.*:ALL,GRANT state=present
                  login_password={{ db_password }} login_user={{ db_username_root }}

    - name: Copy MySQL Configuration
      template: src={{ local_my_cnf_path }} dest={{ remote_my_cnf_path }} force=yes
      sudo: yes

    - name: Restarting MySQL Server
      service: name=mysql state=restarted enabled=true
      sudo: yes

    # Database Dumps

    - name: Check Magento Database
      mysql_db: name={{ db_name_magento }} state=present
                login_password={{ db_password }} login_user={{ db_username_root }}
      notify: Remove Magento Database

    - name: Check Wordpress Database
      mysql_db: name={{ db_name_wordpress }} state=present
                login_password={{ db_password }} login_user={{ db_username_root }}
      notify: Remove Wordpress Database

  handlers:

    # Magento

    - name: Remove Magento Database
      command: rm -rf {{ item }}
      sudo: yes
      notify: Retrieve Magento Database
      with_items:
        - magento-core.sql
        - magento-core.sql.gz

    - name: Retrieve Magento Database
      command: wget {{ database_path }}/magento-core.sql.gz
      sudo: yes
      notify: Decompress Magento Database

    - name: Decompress Magento Database
      command: gzip -d magento-core.sql.gz
      sudo: yes
      notify: Template Magento Database

    - name: Template Magento Database
      template: src=../files/database/magento-template.sql dest=magento-template.sql force=true
      sudo: yes
      notify: Import Magento

    - name: Import Magento
      mysql_db: name={{ db_name_magento }} state=import target={{ item }}.sql
                login_password={{ db_password }} login_user={{ db_username_root }}
      sudo: yes
      with_items:
        - magento-core
        - magento-template

    # Wordpress

    - name: Remove Wordpress Database
      command: rm -rf {{ item }}
      sudo: yes
      notify: Retrieve Wordpress Database
      with_items:
        - wordpress-core.sql
        - wordpress-core.sql.gz

    - name: Retrieve Wordpress Database
      command: wget {{ database_path }}/wordpress-core.sql.gz
      sudo: yes
      notify: Decompress Wordpress Database

    - name: Decompress Wordpress Database
      command: gzip -d wordpress-core.sql.gz
      sudo: yes
      notify: Template Wordpress Database

    - name: Template Wordpress Database
      template: src=../files/database/wordpress-template.sql dest=wordpress-template.sql force=true
      sudo: yes
      notify: Import Wordpress

    - name: Import Wordpress
      mysql_db: name={{ db_name_wordpress }} state=import target={{ item }}.sql
                login_password={{ db_password }} login_user={{ db_username_root }}
      sudo: yes
      with_items:
        - wordpress-core
        - wordpress-template