---
- hosts: all
  name: Nginx
  vars:

    # Local

    document_path: ../files/nginx/

    local_www_root_path: ../../websites/

    local_default_path: "{{ document_path }}default"
    local_info_php_path: "{{ document_path }}info.php"

    local_magento_config: "{{ document_path }}config-magento"
    local_wordpress_config: "{{ document_path }}config-wordpress"

    local_nginx_config: "{{ document_path }}nginx.conf"

    # Remote

    remote_sites_enabled_path: /etc/nginx/sites-enabled
    remote_sites_available_path: /etc/nginx/sites-available
    remote_www_root_path: /usr/share/nginx/www
    remote_nginx_path: "/etc/nginx"

  tasks:

    - name: Include Configuration
      include_vars: ../../ansiblealexa.yml

    # Dependencies and PHP5

    - name: Install Nginx
      apt: pkg=nginx state=installed update_cache=true
      sudo: yes

    - name: Apt Get Update
      command: apt-get update
      sudo: yes

    - name: Install PHP5-FPM
      apt: pkg=php5-fpm state=installed update_cache=true
      sudo: yes

    # SSL Certificate
    - name: Create SSL Certificate
      command: openssl req -new -nodes -x509 -subj "/C=UK/ST=London/L=London/O=LD/CN={{ host_magento }}" -days 3650 -keyout /etc/nginx/magento.key -out /etc/nginx/magento.crt -extensions v3_ca
      sudo: yes

    - name: Start Nginx
      service: name=nginx state=started
      sudo: yes

    # Configuration

    - name: Create Welcome Document
      template: src={{ document_path }}{{ item }} dest={{ remote_www_root_path }} force=yes mode=0644
      sudo: yes
      with_items:
        - index.html
        - default.css

    - name: Create PHP Info Document
      template: src={{ local_info_php_path }} dest={{ remote_www_root_path }} force=yes mode=0644
      sudo: yes

    - name: Create Default Configuration
      copy: src={{ local_default_path }} dest={{ remote_sites_available_path }} force=yes
      sudo: yes

    - name: Template Magento Configuration
      template: src={{ local_magento_config }} dest={{ remote_sites_available_path }}/{{ host_magento }} force=yes
      sudo: yes

    - name: Template Wordpress Configuration
      template: src={{ local_wordpress_config }} dest={{ remote_sites_available_path }}/{{ host_wordpress }} force=yes
      sudo: yes

    # Create Symlinks

    - name: Create Magento Symlink
      command: ln -sf {{ remote_sites_available_path }}/{{ host_magento }} {{ remote_sites_enabled_path }}/{{ host_magento }}
      sudo: yes
      ignore_errors: yes

    - name: Create Wordpress Symlink
      command: ln -sf {{ remote_sites_available_path }}/{{ host_wordpress }} {{ remote_sites_enabled_path }}/{{ host_wordpress }}
      sudo: yes
      ignore_errors: yes

    - name: Copy Nginx Configuration
      template: src={{ local_nginx_config }} dest={{ remote_nginx_path }} force=yes
      ignore_errors: no
      sudo: yes

    # Finalise

    - name: Restart Nginx
      service: name=nginx state=restarted
      sudo: yes