---
- hosts: all
  name: Nginx
  vars:

    # Local

    local_default_path: ../files/nginx/default
    local_index_html_path: ../files/nginx/index.html
    local_info_php_path: ../files/nginx/info.php

    local_magento_config: ../files/nginx/config-magento
    local_wordpress_config: ../files/nginx/config-wordpress

    # Remote

    remote_sites_enabled_path: /etc/nginx/sites-enabled
    remote_sites_available_path: /etc/nginx/sites-available
    remote_www_root_path: /usr/share/nginx/www

  tasks:

    - name: Include Configuration
      include_vars: ../../ansiblealexa.yml

    # Dependencies and PHP5

    - name: Install Nginx
      apt: pkg=nginx state=installed update_cache=true
      sudo: yes

    - name: Apt Get Update
      command: apt-get update
      sudo: yes

    - name: Install PHP5-FPM
      apt: pkg=php5-fpm state=installed update_cache=true
      sudo: yes

    - name: Start Nginx
      service: name=nginx state=started
      sudo: yes

    # Configuration

    - name: Create Welcome Document
      template: src={{ local_index_html_path }} dest={{ remote_www_root_path }} owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Create PHP Info Document
      template: src={{ local_info_php_path }} dest={{ remote_www_root_path }} owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Create Default Configuration
      copy: src={{ local_default_path }} dest={{ remote_sites_available_path }} owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Template Magento Configuration
      template: src={{ local_magento_config }} dest={{ remote_sites_available_path }}/{{ host_magento }} owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Template Wordpress Configuration
      template: src={{ local_wordpress_config }} dest={{ remote_sites_available_path }}/{{ host_wordpress }} owner=root group=root mode=0644 force=yes
      sudo: yes

    # Create Symlinks

    - name: Create Magento Symlink
      command: ln -s {{ remote_sites_available_path }}/{{ host_magento }} {{ remote_sites_enabled_path }}/{{ host_magento }}
      sudo: yes
      ignore_errors: yes

    - name: Create Wordpress Symlink
      command: ln -s {{ remote_sites_available_path }}/{{ host_wordpress }} {{ remote_sites_enabled_path }}/{{ host_wordpress }}
      sudo: yes
      ignore_errors: yes

    # Finalise

    - name: Restart Nginx
      service: name=nginx state=restarted
      sudo: yes