---
- hosts: all
  name: Nginx

  tasks:

    # Dependencies and PHP5

    - name: Install Nginx
      apt: pkg=nginx state=installed update_cache=true
      sudo: yes

    - name: Apt Get Update
      command: apt-get update
      sudo: yes

    - name: Install PHP5-FPM
      apt: pkg=php5-fpm state=installed update_cache=true
      sudo: yes

    - name: Start Nginx
      service: name=nginx state=started
      sudo: yes

    # Configuration

    - name: Create Welcome Document
      copy: src=../files/nginx/index.html dest=/usr/share/nginx/www owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Create Default Configuration
      copy: src=../files/nginx/default dest=/etc/nginx/sites-available owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Create Magento Configuration
      copy: src=../files/nginx/192.168.50.4 dest=/etc/nginx/sites-available owner=root group=root mode=0644 force=yes
      sudo: yes

    - name: Create Wordpress Configuration
      copy: src=../files/nginx/192.168.50.5 dest=/etc/nginx/sites-available owner=root group=root mode=0644 force=yes
      sudo: yes

    # Create Symlinks

    - name: Create Magento Symlink
      command: ln -s /etc/nginx/sites-available/192.168.50.4 /etc/nginx/sites-enabled/192.168.50.4
      sudo: yes
      ignore_errors: yes

    - name: Create Wordpress Symlink
      command: ln -s /etc/nginx/sites-available/192.168.50.5 /etc/nginx/sites-enabled/192.168.50.5
      sudo: yes
      ignore_errors: yes

    # Finalise

    - name: Restart Nginx
      service: name=nginx state=restarted
      sudo: yes