---
- hosts: all
  name: NPM
  vars:

    magento_root_path: /usr/share/nginx/www/magento

  tasks:

    - name: Include Configuration
      include_vars: ../../ansiblealexa.yml

    - name: Install NPM Modules
      apt: pkg={{ item }} state=installed update_cache=true install_recommends=no
      sudo: yes
      with_items:
        - python-software-properties
        - software-properties-common
        - python
        - g++
        - make

    - name: Add Node.js Repository
      shell: echo "" | add-apt-repository ppa:chris-lea/node.js
      sudo: yes

    - name: Apt-Get Update
      shell: apt-get update
      sudo: yes

    - name: Install NPM Modules
      apt: pkg={{ item }} state=installed update_cache=true
      sudo: yes
      with_items:
        - nodejs

    - name: Install Dependencies
      npm: path={{ magento_root_path }}
      sudo: yes

    - name: Install Bower
      npm: name=bower global=yes
      sudo: yes

    - name: Install Bower Dependencies
      shell: bower install chdir={{ magento_root_path }}