---
- hosts: all
  name: NPM
  vars:

    magento_root_path: /usr/share/nginx/www/magento

  tasks:

    - name: Include Configuration
      include_vars: ../../ansiblealexa.yml

    - name: Apt Get Update
      command: apt-get update
      sudo: yes

    - name: Install Python-Software-Properties
      apt: pkg=python-software-properties state=installed update_cache=true force=true
      sudo: yes

    - name: Update NPM
      command: echo "" | sudo add-apt-repository ppa:chris-lea/node.js
      sudo: yes

    - name: Apt Get Update
      command: apt-get update
      sudo: yes

    - name: Update Node.js
      apt: pkg=nodejs state=installed update_cache=true force=true
      sudo: yes

    - name: Install NPM Modules
      command: "chdir={{ magento_root_path }} npm install"

    - name: Build Magento Dependencies
      command: "chdir={{ magento_root_path }} node_modules/grunt-cli/bin/grunt build"