---
- hosts: all
  name: PHP
  vars:

    # Local

    local_apc_ini_path: ../files/php/apc.ini

    # Remote

    remote_apc_ini_path: /etc/php5/conf.d

  tasks:

    # PHP Dependencies

    - name: Install PHP-MySQL Module
      apt: pkg=php5-mysql state=installed update_cache=true
      sudo: yes

    - name: Install PHP-Curl Module
      apt: pkg=php5-curl state=installed update_cache=true
      sudo: yes

    - name: Install PHP-Memcache Module
      apt: pkg=php5-memcache state=installed update_cache=true
      sudo: yes

    - name: Install PHP-MCrypt Module
      apt: pkg=php5-mcrypt state=installed update_cache=true
      sudo: yes

    - name: Install PHP-CLI Module
      apt: pkg=php5-cli state=installed update_cache=true
      sudo: yes

    - name: Install PHP-APC Module
      apt: pkg=php-apc state=installed update_cache=true
      sudo: yes

    # Finalise

    - name: Restart Nginx
      service: name=nginx state=restarted
      sudo: yes

    - name: Restart PHP
      service: name=php5-fpm state=reloaded
      sudo: yes