---
- hosts: all
  name: PHP
  vars:

    # Local

    local_apc_ini_path: ../files/php/apc.ini

    # Remote

    remote_apc_ini_path: /etc/php5/conf.d

  tasks:

    # PHP Dependencies

    - name: Install PHP-MySQL Module
      apt: pkg=php5-mysql state=installed update_cache=true
      sudo: yes

    - name: Install PHP-Curl Module
      apt: pkg=php5-curl state=installed update_cache=true
      sudo: yes

    - name: Install PHP-Memcache Module
      apt: pkg=php5-memcache state=installed update_cache=true
      sudo: yes

    - name: Install PHP-CLI Module
      apt: pkg=php5-cli state=installed update_cache=true
      sudo: yes

    # APC Dependency

    - name: Install PHP-PEAR Module
      apt: pkg=php-pear state=installed update_cache=true
      sudo: yes

    - name: Install PHP-Dev Module
      apt: pkg=php5-dev state=installed update_cache=true
      sudo: yes

    - name: Install Build Essential Module
      apt: pkg=build-essential state=installed update_cache=true
      sudo: yes

    - name: Install Apache-Prefork-Dev Module
      apt: pkg=apache2-prefork-dev state=installed update_cache=true
      sudo: yes

    - name: Install APC
      command: printf "\n" | sudo pecl install apc
      sudo: yes

    - name: Create APC Configuration
      copy: src={{ local_apc_ini_path }} dest={{ remote_apc_ini_path }} owner=root group=root mode=0644 force=yes
      sudo: yes

    # Finalise

    - name: Restart Nginx
      service: name=nginx state=restarted
      sudo: yes

    - name: Restart PHP
      service: name=php5-fpm state=reloaded
      sudo: yes