---
- hosts: all
  name: PHP
  vars:

    # Local

    local_apc_ini_path: ../files/php/apc.ini

    # Remote

    remote_apc_ini_path: /etc/php5/conf.d

  tasks:

    # PHP Dependencies

    - name: Install PHP Modules
      apt: pkg={{ item }} state=installed update_cache=true install_recommends=no
      sudo: yes
      with_items:
        - php5-mysql
        - php5-curl
        - php5-memcache
        - php5-mcrypt
        - php5-cli
        - php-apc

    # Finalise

    - name: Restart Nginx
      service: name=nginx state=restarted
      sudo: yes

    - name: Restart PHP
      service: name=php5-fpm state=reloaded
      sudo: yes