---
- hosts: all
  name: PHP
  vars:

    # Local

    local_apc_ini_path: ../files/php/apc.ini
    local_xdebug_ini_path: ../files/php/xdebug.ini

    # Remote

    remote_php_ini_path: /etc/php5/conf.d

  tasks:

    - name: Include Configuration
      include_vars: ../../ansiblealexa.yml

    # Memcache
    - name: Install Memcache
      apt: pkg=memcached state=installed update_cache=true
      sudo: yes

    # PHP Dependencies

    - name: Install PHP Modules
      apt: pkg={{ item }} state=installed update_cache=true install_recommends=no
      sudo: yes
      with_items:
        - php5-mysql
        - php5-curl
        - php5-memcache
        - php5-mcrypt
        - php5-cli
        - php-apc
        - php-pear
        - php5-dev

    # Install XDebug

    - name: Uninstall XDebug
      command: sudo pecl uninstall xdebug
      ignore_errors: no

    - name: Install XDebug
      command: sudo pecl install xdebug
      ignore_errors: no

    - name: Looking for a XDebug instance
      shell: find /usr/lib/ -name 'xdebug.so' 2> /dev/null
      register: xdebugFind
      ignore_errors: no

    # Print the shell task's stdout.
    - name: XDebug instance path
      debug: msg="XDebug found in path '{{ xdebugFind.stdout }}'"

    - name: Copy XDebug Configuration
      template: src={{ local_xdebug_ini_path }} dest={{ remote_php_ini_path }} force=yes
      sudo: yes

    # Finalise

    - name: Restart Nginx
      service: name=nginx state=restarted
      sudo: yes

    - name: Restart PHP
      service: name=php5-fpm state=reloaded
      sudo: yes