---
- hosts: all
  name: Repository
  connection: local
  vars:

    local_magento_repository_path: ../../websites/magento
    local_wordpress_repository_path: ../../websites/wordpress

  tasks:

    - name: Include Configuration
      include_vars: ../../ansiblealexa.yml

    # Databases

    - name: Decompress Magento
      command: gzip -d ../files/database/magento.sql.gz

    - name: Decompress Wordpress
      command: gzip -d ../files/database/wordpress.sql.gz

    # Magento

    - name: Check Magento
      stat: path=../../websites/magento/.git
      register: check_magento_path

    - name: Clone Magento
      git: repo={{ repository_magento }} dest={{ local_magento_repository_path }}
      when: check_magento_path.stat.exists == false

    - name: Clear Magento Lightspeed
      command: rm -rf /usr/share/nginx/www/magento/web-root/var/lightspeed/*
      ignore_errors: yes

    - name: Clear Magento Cache
      command: rm -rf /usr/share/nginx/www/magento/web-root/var/cache/*
      ignore_errors: yes

    # Wordpress

    - name: Check Wordpress
      stat: path=../../websites/wordpress/.git
      register: check_wordpress_path

    - name: Clone Wordpress
      git: repo={{ repository_wordpress }} dest={{ local_wordpress_repository_path }}
      when: check_wordpress_path.stat.exists == false