---
- hosts: all
  name: Repository
  connection: local

  tasks:

    # Magento

    - name: Check Magento
      stat: path=../../websites/magento/.git
      register: check_magento_path

    - name: Clone Magento
      git: repo=git@github.com:alexandalexa/hephaestus.git dest=../../websites/magento
      when: check_magento_path.stat.exists == false

    # Wordpress

    - name: Check Wordpress
      stat: path=../../websites/wordpress/.git
      register: check_wordpress_path

    - name: Clone Wordpress
      git: repo=git@github.com:alexandalexa/Wordpress.git dest=../../websites/wordpress
      when: check_wordpress_path.stat.exists == false